name: skydb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      docker build . --file Dockerfile --tag skydb:$(date +%s)
    - name: Install the package
      run: pip install --editable .
    - name: Run the unit test
      run: pytyhon -m unittest
      
