name: skydb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build the distributoin
      run: python -m build
    - name: Build the Docker image
      run: make build
    - name: Run the unit test in the container
      run: docker run   --interactive --tty --ip 0.0.0.0 --rm --env DISPLAY=host.docker.internal:0 -v $(pwd):/opt/skydb images.canfar.net/uvickbos/skydb:0.1 pytest
      
